name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: host
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

  test:
    runs-on: host
    needs: build
    steps:
    - name: Run tests
      run: npm test
    - name: Get runner public IP
      run: curl ifconfig.me
  deploy:
    runs-on: host
    needs: test
    steps:
    - name: Log in to DockerHub
      run: |
         if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
           echo "Docker credentials are not set!" >&2
           exit 1
         fi
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  deliver:
      runs-on: host
      needs: deploy
      steps:
      
      - name: Build Docker image
        run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/my-ci-app:latest .
  dispatch:
     runs-on: host
     needs: deliver
     steps:

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-ci-app:latest
      

